---
exclude_paths:
- ".git/"
- "**.svg"
- "**.wsdl"
- "**.xml"
- "**.xsd"
- "**.yaml"
- "**.yml"
- "spec/"
- "test/"
- "tmp/"
- "lib/gems/pending/*/test/"
- "lib/gems/pending/metadata/linux/test/Packages"
- "lib/gems/pending/metadata/linux/test/tc_LinuxUtils.rb"
- "lib/gems/pending/VcoWebService/vmwo.wsdl"
- "lib/gems/pending/VMwareWebService/wsdl41/"
engines:
  brakeman:
    # very slow :sad_panda:
    enabled: false
  bundler-audit:
    # requires Gemfile.lock
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    # let's enable later
    enabled: false
  markdownlint:
    # let's enable later
    enabled: false
  rubocop:
    enabled: true
    config: '.rubocop_cc.yml'
prepare:
  fetch:
  - url: "https://raw.githubusercontent.com/ManageIQ/guides/master/.rubocop_base.yml"
    path: ".rubocop_base.yml"
  - url: "https://raw.githubusercontent.com/ManageIQ/guides/master/.rubocop_cc_base.yml"
    path: ".rubocop_cc_base.yml"
ratings:
  paths:
  - Gemfile.lock
  - "**.rake"
  - "**.rb"
