---
exclude_paths:
- ".git/"
- "**.xml"
- "**.yaml"
- "**.yml"
- spec/
- test/
- lib/gems/pending/*/test/
engines:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: false
  markdownlint:
    enabled: false
  rubocop:
    enabled: true
    config: ".rubocop_cc.yml"
    channel: rubocop-0-69
prepare:
  fetch:
  - url: https://raw.githubusercontent.com/ManageIQ/guides/master/.rubocop_base.yml
    path: ".rubocop_base.yml"
  - url: https://raw.githubusercontent.com/ManageIQ/guides/master/.rubocop_cc_base.yml
    path: ".rubocop_cc_base.yml"
ratings:
  paths:
  - Gemfile.lock
  - "**.rake"
  - "**.rb"
