#
# Overrides
#
GlobalVars:
  AllowedVariables:
  # Loggers
  - $log
  - $vim_log
#
# Special Exclusions
#
AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - lib/gems/pending/VMwareWebService/wsdl41/vimws25MappingRegistry.rb
Metrics/LineLength:
  Exclude:
    - Gemfile
Style/ExtraSpacing:
  Exclude:
    - Gemfile
