#
# Overrides
#
GlobalVars:
  AllowedVariables:
  # Loggers
  - $log
  - $vim_log
#
# Special Exclusions
#
AllCops:
  Exclude:
    - lib/gems/pending/VMwareWebService/wsdl41/vimws25MappingRegistry.rb
